export const ActionTypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    SET_CURRENT_PRODUCT:"SET_CURRENT_PRODUCT",
    REMOVE_CURRENT_PRODUCT:"REMOVE_CURRENT_PRODUCT",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    INCREMENT:"INCREMENT",
    DECREMENT:"DECREMENT"
}